import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "@next/font/google";

import { getServerSession } from "next-auth";
import AuthProvider from "@/components/SessionProvider";
import { authOptions } from "@/lib/auth";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Real Estate App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={dmSans.className}>
        <AuthProvider session={session}>{children}</AuthProvider>
      </body>
    </html>
  );
}
